# Copyright 2004-2006 Daniel Henninger <jadestorm@nc.rr.com>
# Licensed for distribution under the GPL version 2, check COPYING for details

# -- DO NOT EDIT THIS FILE --
# This file is -not- to be edited by hand.  It is simply defaults.
# Actual configuration should be done in config.xml in the root directory.
# -- DO NOT EDIT THIS FILE --

if type(True) != bool: from bool import bool

jid = "icq.localhost"
compjid = ""
spooldir = ".."
pid = ""
mainServer = "127.0.0.1"
mainServerJID = ""
website = ""
reactor = ""
port = 5347
webport = 0
secret = "secret"
lang = "en"
encoding = "iso-8859-1"
icqServer = "login.icq.com"
icqPort = 5238
sessionGreeting = ""
registerMessage = ""
crossChat = bool(False)
debugLevel = 0 # 0->None, 1->Traceback, 2->WARN,ERROR, 3->INFO,WARN,ERROR
debugFile = ""
disableRegister = bool(False)
disableXHTML = bool(False)
enableAutoInvite = bool(False)
tracebackDebug = bool(False)
socksProxyServer = ""
socksProxyPort = 0
admins = []
xdbDriver = "xmlfiles"
xdbDriver_mysql = {}
xdbDriver_xmlfiles = {}
useXCP = bool(False)
useJ2Component = bool(False)
saslUsername = ""
avatarsOnlyOnChat = bool(False)
disableDefaultAvatar = bool(False)
disableAvatars = bool(False)
enableWebPresence = bool(False)
disableMailNotifications = bool(False)
