# Copyright 2004-2005 Daniel Henninger <jadestorm@nc.rr.com>
# Licensed for distribution under the GPL version 2, check COPYING for details

# -- DO NOT EDIT THIS FILE --
# This file is -not- to be edited by hand.  It is simply defaults.
# Actual configuration should be done in config.xml in the root directory.
# -- DO NOT EDIT THIS FILE --

if type(True) != bool: from bool import bool

jid = "icq.localhost"
compjid = ""
spooldir = ".."
pid = ""
mainServer = "127.0.0.1"
mainServerJID = ""
website = ""
reactor = ""
port = "5347"
webport = ""
secret = "secret"
lang = "en"
encoding = "iso-8859-1"
icqServer = "login.icq.com"
icqPort = "5238"
sessionGreeting = ""
registerMessage = ""
crossChat = bool(False)
debugOn = bool(False)
debugLog = ""
extendedDebugOn = bool(False)
disableRegister = bool(False)
disableXHTML = bool(False)
enableAutoInvite = bool(False)
tracebackDebug = bool(False)
socksProxyServer = ""
socksProxyPort = ""
admins = []
xdbDriver = "xmlfiles"
xdbDriver_mysql = {}
xdbDriver_xmlfiles = {}
useXCP = bool(False)
useJ2Component = bool(False)
saslUsername = ""
avatarsOnlyOnChat = bool(False)
disableDefaultAvatar = bool(False)
disableAvatars = bool(False)
disableWebPresence = bool(False)
disableMailNotifications = bool(False)
