# -- DO NOT EDIT THIS FILE --
# This file is -not- to be edited by hand.  It is simply defaults.
# Actual configuration should be done in config.xml in the root directory.
# -- DO NOT EDIT THIS FILE --

jid = "icq.localhost"
spooldir = ".."
pid = "../PyICQt.pid"
mainServer = "127.0.0.1"
port = "5347"
webport = ""
websecret = ""
secret = "secret"
lang = "en"
encoding = "iso-8859-1"
icqServer = "login.icq.com"
icqPort = "5238"
sessionGreeting = ""
registerMessage = ""
crossChat = False
debugOn = False
debugLog = ""
extendedDebugOn = False
disableRegister = False
socksProxyServer = ""
socksProxyPort = ""
