# Copyright 2005-2006 Daniel Henninger <jadestorm@nc.rr.com>
# Licensed for distribution under the GPL version 2, check COPYING for details

XMPP_STANZAS	= "urn:ietf:params:xml:ns:xmpp-stanzas"
DISCO		= "http://jabber.org/protocol/disco"
DISCO_ITEMS	= DISCO + "#items"
DISCO_INFO	= DISCO + "#info"
COMMANDS	= "http://jabber.org/protocol/commands"
CAPS		= "http://jabber.org/protocol/caps"
SUBSYNC		= "http://delx.cjb.net/protocol/roster-subsync"
MUC		= "http://jabber.org/protocol/muc"
MUC_USER	= MUC + "#user"
FEATURE_NEG	= "http://jabber.org/protocol/feature-neg"
SI		= "http://jabber.org/protocol/si"
FT		= "http://jabber.org/protocol/si/profile/file-transfer"
S5B		= "http://jabber.org/protocol/bytestreams"
IBB		= "http://jabber.org/protocol/ibb"
IQGATEWAY	= "jabber:iq:gateway"
IQVERSION	= "jabber:iq:version"
IQREGISTER	= "jabber:iq:register"
IQROSTER	= "jabber:iq:roster"
IQAVATAR	= "jabber:iq:avatar"
IQOOB		= "jabber:iq:oob"
VCARD		= "vcard-temp"
XOOB		= "jabber:x:oob"
XCONFERENCE	= "jabber:x:conference"
XEVENT		= "jabber:x:event"
XHTML		= "http://jabber.org/protocol/xhtml-im"
